# Generated by Django 4.2.4 on 2023-08-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
                ('gender', models.CharField(choices=[('girl', 'girl'), ('boy', 'boy'), ('man', 'man'), ('woman', 'woman')], max_length=15)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
