# Generated by Django 4.2.4 on 2023-08-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='footwear',
            new_name='shoes',
        ),
    ]
