# Generated by Django 4.2.4 on 2023-08-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit_accessory',
            name='outfit',
        ),
        migrations.RemoveField(
            model_name='outfit_occasion',
            name='outfit',
        ),
        migrations.DeleteModel(
            name='Outfit',
        ),
        migrations.DeleteModel(
            name='Outfit_Accessory',
        ),
        migrations.DeleteModel(
            name='Outfit_Occasion',
        ),
    ]
