# Generated by Django 4.2.4 on 2023-08-20 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('outfit', '0003_outfit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.account'),
        ),
    ]
