# Generated by Django 4.2.4 on 2023-08-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0004_alter_outfit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='user',
        ),
    ]
